PROJECT_NAME: imali-demo
HOST_NAME: rehive-build-server
NAMESPACE: imali-demo-staging
IMAGE: gcr.io/rehive-services/imali-demo-staging
VIRTUAL_HOST: imali.s.demos.rehive.io
CLUSTER: staging
CLUSTER_PROJECT: rehive-services
